image: gitlab/dind

stages:
  - build
 # - deploy

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  #- eval $(ssh-agent -s)
  - mkdir -p /home/appuser/.ssh
  - touch /home/appuser/.ssh/id_rsa.pub /home/appuser/.ssh/id_rsa
  - chmod -R 700 /home/appuser/.ssh
  - whoami
  - ls -l /home/appuser/.ssh
  - echo "$ssh_private_key" > /home/appuser/.ssh/id_rsa
  - echo "$ssh_pub_key" > /home/appuser/.ssh/id_rsa.pub
  - ssh-copy-id -i /home/appuser/.ssh/id_rsa.pub appuser@178.154.201.156
  - ssh -vvv -T -i /home/appuser/.ssh/id_rsa.pub -o StrictHostKeyChecking=no appuser@178.154.201.156
  - docker login -u $DockerHubLogin -p $DockerhubToken
build_job:
  stage: build
  script:
    - docker build ./mongo/ --tag apocatastasys/mongo  
    - docker build ./rabbitmq/ --tag apocatastasys/rabbitmq
    - docker build ./search_engine_crawler/ --tag apocatastasys/crawler:1.0
    - docker build ./search_engine_ui/ --tag apocatastasys/app:1.0
    - docker images
    - docker push apocatastasys/rabbitmq
    - docker push apocatastasys/crawler:1.0
    - docker push apocatastasys/app:1.0
    - docker push apocatastasys/mongo
  tags:
    - docker 


