image: gitlab/dind

stages:
  - build
 # - deploy

before_script:
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - touch ~/.ssh/id_rsa #/home/appuser/.ssh/id_rsa.pub
  - chmod -R 700 ~/.ssh
  #- ssh-add <(echo "$ssh_private_key")
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - echo "${ssh_private_key}" | ssh-add - #/home/appuser/.ssh/id_rsa
  #- echo "$ssh_pub_key" | tr -d '\r' | ssh-add - ~/.ssh/id_rsa.pub
  - ssh -vvv -o StrictHostKeyChecking=no deployer@178.154.201.156
  - docker login -u $DockerHubLogin -p $DockerhubToken
build_job:
  stage: build
  script:
    - docker build ./mongo/ --tag apocatastasys/mongo  
    - docker build ./rabbitmq/ --tag apocatastasys/rabbitmq
    - docker build ./search_engine_crawler/ --tag apocatastasys/crawler:1.0
    - docker build ./search_engine_ui/ --tag apocatastasys/app:1.0
    - docker images
    - docker push apocatastasys/rabbitmq
    - docker push apocatastasys/crawler:1.0
    - docker push apocatastasys/app:1.0
    - docker push apocatastasys/mongo
  tags:
    - shell-runner

 


