image: gitlab/dind

stages:
  - build
 # - deploy

before_script:
  - eval $(docker-machine tcp://178.154.201.156:2376)

build_job:
  stage: build
  script:
    - cd search_engine_ui
    - docker build -t app:1.0 .
    - docker run --name App1.2 -p 8000:8000 app:1.0
  tags:
    - docker

#deploy_job:
 # stage: deploy
  #script:
   # - docker run --name App:1.2 -p 8000:8000 app:1.0
