image: gitlab/dind

stages:
  - build
 # - deploy

before_script:
  - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
  - su - deployer
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  - chmod -R 700 ~/.ssh
  - whoami
  - echo "$ssh_private_key" | tr -d '\r' | ssh-add ~/.ssh/id_rsa
  - ls -l ~/.ssh
  - ssh -vvv -tt -l deployer -o StrictHostKeyChecking=no deployer@178.154.201.156
  - docker login -u $DockerHubLogin -p $DockerhubToken
build_job:
  stage: build
  script:
    - docker build ./mongo/ --tag apocatastasys/mongo  
    - docker build ./rabbitmq/ --tag apocatastasys/rabbitmq
    - docker build ./search_engine_crawler/ --tag apocatastasys/crawler:1.0
    - docker build ./search_engine_ui/ --tag apocatastasys/app:1.0
    - docker images
    - docker push apocatastasys/rabbitmq
    - docker push apocatastasys/crawler:1.0
    - docker push apocatastasys/app:1.0
    - docker push apocatastasys/mongo
  tags:
    - docker 


