stages:
  - build

build_job:
  stage: build
  script:
    - git clone http://root:YzgUo7x8aX9-S5NJTzdz@178.154.201.156/projectgroup/project.git
    - hostname
    - cd search_engine_ui
    - pip install -r requirements.txt
    - cd ui
    - FLASK_APP=ui.py gunicorn ui:app -b   178.154.201.156
  tags:
    - shell-runner

 # variables:
#    MONGO: 178.154.201.156
  #  MONGO_PORT: 27017
   # DOCKER_USERNAME: appuser
    #DOCKER_HOST: tcp://178.154.201.156:2376
    #DOCKER_MACHINE_NAME: project-host    
