image: gitlab/dind

stages:
  - build
  - deploy

before_script:
  stage: build
    - docker login -u $DockerHubLogin -p $DockerhubToken
  
build_job:
  stage: build
  script:
    #- docker build ./mongo/ --tag apocatastasys/mongo  
    - docker build ./rabbitmq/ --tag apocatastasys/rabbitmq
    #- docker build ./search_engine_crawler/ --tag apocatastasys/crawler:1.0
    #- docker build ./search_engine_ui/ --tag apocatastasys/app:1.0
    #- docker images
    - docker push apocatastasys/rabbitmq
    #- docker push apocatastasys/crawler:1.0
    #- docker push apocatastasys/app:1.0
    #- docker push apocatastasys/mongo
  tags:
    - docker
    
deploy_job:
  stage: deploy
  script: 
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$ssh_private_key" > ~/.ssh/id_rsa
    - echo "$ssh_pub_key" > ~/.ssh/id_rsa.pub
    - echo "$authorized_keys" > ~/.ssh/authorized_keys
    - chmod -R 700 ~/.ssh
    - cat ~/.ssh/id_rsa.pub
    - ssh-add ~/.ssh/id_rsa
    - scp docker-compose.yaml deployer@178.154.201.156:~
    - ssh deployer@178.154.201.156 "hostname && pwd && /usr/bin/docker-compose up"
  tags:
    - shell-runner


