image: gitlab/dind

stages:
  #- build
  - deploy

deploy_job:
  stage: deploy
  script: 
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - echo "$ssh_private_key" > ~/.ssh/id_rsa
    - echo "$ssh_pub_key" > ~/.ssh/id_rsa.pub
    - echo "$authorized_keys" > ~/.ssh/authorized_keys
    - chmod -R 700 ~/.ssh
    - cat ~/.ssh/id_rsa.pub
    - ssh-add ~/.ssh/id_rsa
    - scp docker-compose.yaml deployer@178.154.201.156:~
    - ssh deployer@178.154.201.156; hostname; pwd; /usr/bin/docker-compose up
  tags:
    - shell-runner


