image: gitlab/dind

stages:
  - build
 # - deploy

before_script:
  - eval $(ssh-agent -s)
  - mkdir -p ~/.ssh
  #- touch ~/.ssh/id_rsa #/home/deployer/.ssh/id_rsa
  - echo "$ssh_private_key" > ~/.ssh/id_rsa
  - echo "$ssh_pub_key" > ~/.ssh/id_rsa.pub
  - echo "$authorized_keys" > ~/.ssh/authorized_keys
  - chmod -R 700 ~/.ssh
  - cat ~/.ssh/id_rsa.pub
  #- ssh-copy-id -f -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@178.154.201.156
  - ssh-add ~/.ssh/id_rsa
  #- echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  #- chmod 644 ~/.ssh/known_hosts
  #- ssh-add <(echo "$ssh_private_key" | base64 -d)
  #- echo "$ssh_pub_key" | tr -d '\r' | ssh-add - ~/.ssh/id_rsa.pub
  - ssh -vvv deployer@178.154.201.156
  - docker login -u $DockerHubLogin -p $DockerhubToken
build_job:
  stage: build
  script:
    - docker build ./mongo/ --tag apocatastasys/mongo  
    - docker build ./rabbitmq/ --tag apocatastasys/rabbitmq
    - docker build ./search_engine_crawler/ --tag apocatastasys/crawler:1.0
    - docker build ./search_engine_ui/ --tag apocatastasys/app:1.0
    - docker images
    - docker push apocatastasys/rabbitmq
    - docker push apocatastasys/crawler:1.0
    - docker push apocatastasys/app:1.0
    - docker push apocatastasys/mongo
  tags:
    - shell-runner

 


