image: gitlab/dind

stages:
  - build
 # - deploy

before_script:
  - docker info

build_job:
  stage: build
  script:
    - cd search_engine_ui
    - docker build -t app:1.0 .
    - docker save -o app1.0.tar app:1.0
    - scp app1.0.tar ubuntu:1q2w3e4r@178.154.201.156:~/
  tags:
    - docker 

#deploy_job:
 # stage: deploy
  #script:
   # - docker run --name App:1.2 -p 8000:8000 app:1.0
