image: gitlab/dind

stages:
  - build
 # - deploy

before_script:
  - whoami
  - docker login -u apocatastasys -p 3c150b4e-abf8-430e-904e-176cda69a3f3
build_job:
  stage: build
  script:
    - docker run --tag apocatastasys/mongo -d --name mymongo -p 27017:27017 mongo  
    - docker build ./rabbitmq/ --tag apocatastasys/rabbitmq
    - docker build ./search_engine_crawler/ --tag apocatastasys/crawler:1.0
    - docker build ./search_engine_ui/ --tag apocatastasys/app:1.0
    - docker images
    - docker push apocatastasys/rabbitmq
    - docker push apocatastasys/crawler:1.0
    - docker push apocatastasys/app:1.0
    - docker push apocatastasys/mongo
  tags:
    - docker 


