image: gitlab/dind

stages:
  - build
 # - deploy

before_script:
  - whoami
  - docker login -u apocatastays -p 6c4ee3d4-ff7f-45bb-930c-a6af7133134d https://index.docker.io
build_job:
  stage: build
  script:
    #- docker run  -d --name mymongo -p 27017:27017 mongo
    #- docker push 
    - docker build ./rabbitmq/ -t rabbitmq
    - docker push rabbitmq
    #- docker run -d --name rabbitmq1.0 rabbitmq 
    #- docker build ./search_engine_crawler/ -t crawler:1.0
    #- docker run -d --name Crawler crawler:1.0
    #- docker build ./search_engine_ui/ -t app:1.0
    #- docker run --name App1.0 -p 8000:8000 app:1.0
  tags:
    - docker 

