version: '3'
services:
  mymongo:
    image: apocatastasys/mongo
    ports:
      - 27017:27017
  myrabbitmq:
    image: apocatastasys/rabbitmq:latest
  mycrawler:
    image: apocatastasys/crawler:1.0
  myapp:
    image: apocatastasys/app:1.0
    ports:
      - 8000:8000
