version: '3'
services:
  prometheus:
    image: apocatastasys/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
  mymongo:
    image: apocatastasys/mongo
    ports:
      - 27017:27017
  myrabbitmq:
    image: apocatastasys/rabbitmq:latest
    ports:
      - 5672:5672
  mycrawler:
    image: apocatastasys/crawler:1.0
  myapp:
    image: apocatastasys/app:1.0
    ports:
      - 8000:8000
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
volumes:
  prometheus_data:
