version: '3'
services:

  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - front_net
      - back_net

  post:
    image: ${USER_NAME}/post
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  ui:
    build: src/ui
    image: ${USER_NAME}/ui:${UI_VERSION}
    ports: 
      - ${UI_PORT}:9292/tcp
    networks:
      - front_net
    volumes:
      - ui:/data/ui
      
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
        
networks:
  front_net:
  back_net:
volumes:
  post_db:
  ui:
